version: "2"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - eldo-network
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm run docker"]
    volumes:
      - .:/var/www
      - /var/www/node_modules
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    networks:
      - eldo-network
networks: 
  eldo-network:
    driver: bridge