version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:mongodb
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm start"]
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
